# @format

# {
#   "token_secret": "long-token_secret",
#   "db": {
#     "host": "localhost",
#     "port": 27017,
#     "name": "test"
#   }
# }

token_secret: long-token_secret
db:
  host: localhost
  port: 27017
